### ISSUE TITLE
Feature Request: Weak GitHub OIDC Claim Verification

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [suzuki-shunsuke/ghalint#204]
Ensure IAM policies to integrate with GitHub's OIDC provider validate the subject claim to limit the context in which the role can be assumed. If there are no conditions or the condition is too permissive, it could allow unintended repositories to assume the role.

Doc reference - https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.

> If there are no conditions or the condition is too permissive, it could allow unintended repositories to assume the role.

This is AWS IAM Role's settings, not GitHub Actions.

**Comment by suzuki-shunsuke** [comment]
If you have any ideas of new lint rules, could you tell us the example?

e.g.

https://github.com/suzuki-shunsuke/ghalint/blob/187f8c9011c851ebb0bd7fe9d17d6f07c0f82e9b/README.md?plain=1#L29-L81

**Comment by bviswanathan-exelixis** [comment]
@suzuki-shunsuke I don't have good idea on linting rules but if we can create rules for checking as written in this blog around github security best practices - https://engineering.salesforce.com/github-actions-security-best-practices-b8f9df5c75f5/ then that can be run as part of ghalint tool.

**Comment by bviswanathan-exelixis** [comment]
Something like this one - https://github.com/turbot/steampipe-mod-github-sherlock

**Comment by suzuki-shunsuke** [comment]
I read the blog post https://engineering.salesforce.com/github-actions-security-best-practices-b8f9df5c75f5/ and created some issues.

- https://github.com/suzuki-shunsuke/ghalint/issues/209
- https://github.com/suzuki-shunsuke/ghalint/issues/208
- https://github.com/suzuki-shunsuke/ghalint/issues/207
- https://github.com/suzuki-shunsuke/ghalint/issues/206

**Comment by suzuki-shunsuke** [comment]
I close this issue because the problem and action are not clear.
We need to clarify the issue and action in the scope of ghalint (GitHub Actions Linter).
