### ISSUE TITLE
Feature Request: Check if Binary Artifacts Stored in SCM

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [suzuki-shunsuke/ghalint#230]
Check for binary / executable artifacts (ex. *.jar, *.class, *.so, etc.) stored in the Git repository (local or on github). Binary artifacts should not be committed to Git and should be only be built from source by CI/CD system.

Binary artifacts are opaque when compared to plain text source code, which can be audited and it's easy to keep track of changes and enforce code review in Pull Requests.

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
But I don't think this is the scope of ghalint.
ghalint is a linter for GitHub Actions Workflows.

**Comment by bviswanathan-exelixis** [comment]
Thanks @suzuki-shunsuke. Is it possible to expand the scope, i.e ghalint -> ghlint?.

**Comment by suzuki-shunsuke** [comment]
No. We won't expand the scope of ghalint.
We should develop other tools instead.

**Comment by bviswanathan-exelixis** [comment]
Sounds good, thanks @suzuki-shunsuke
