### ISSUE TITLE
Feature Request: Branch protection checks

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [suzuki-shunsuke/ghalint#231]
- Branch Protection Check: Repository Branch Protection

Checks if github repo branches don't have branch protection turned on

- Branch Protection Check: Default Branch Deletion

Checks if repo's default branch's allow deletion is turned on

- Branch Protection Check: Allows Force Pushes

Checks for repository config that allows force pushes to default branch.

- Branch Protection Check: Allows Merge Commit History

Checks for repo config that allows merge commits to be pushed to default branch.

- Branch Protection Check: Allows Unresolved Conversations

Check if all conversation is resolved before merging 

- Branch Protection Check: No Code Owners Required

Checks for repository config that does not require reviews from a designated code owner. 

- Branch Protection Check: No Commit Signature Required

Checks for repository config that does not require commits to be cryptographically signed.

- Branch Protection Check: Protections not Enforced for Admins

Checks that the branch protection settings are enforced for regular users and repository administrators.

- Branch Protection Check: Stale Reviews Remain Valid

Checks for repository config that keeps review approvals even after new commits are pushed in the Pull Request.

- Branch Protection Check: No Approvals Required

Checks if repository config allows zero approvals before merging a PR to default branch.

- Branch Protection Check: No Status Checks Required

Checks for repository config that requires no (zero) status checks to pass before a PR can be merged.

- Branch Protection Check: Allows Reviewer to Self-Review Their Own Changes

Checks for repository config that allows a PR reviewer to push new commits that bypass otherwise enforced peer review approval.

**Comment by suzuki-shunsuke** [comment]
As I said https://github.com/suzuki-shunsuke/ghalint/issues/230 , this isn't the scope of ghalint.
We should develop other tools instead.
