### ISSUE TITLE
Feature Request: Allow exclude `deny_inherit_secrets`

### ISSUE THREAD

**Issue by ponkio-o** [suzuki-shunsuke/ghalint#463]
Hi, @suzuki-shunsuke 
Thank you for developing a great tool.

If you want to use [Environment Secrets](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets) in [Reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows),you must pass the secret with `secrets: inherit`.

https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

So I'd like to be able to exlude `deny_inherit_secrets` in the configuration file as well.

ref. https://x.com/ponkio_o/status/1798593685728514465 (JP)

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal!

- https://github.com/suzuki-shunsuke/ghalint/pull/464

**Comment by suzuki-shunsuke** [comment]
- https://github.com/actions/runner/issues/1490#issuecomment-1717389283

**Comment by suzuki-shunsuke** [comment]
v0.2.10 is out 🎉
https://github.com/suzuki-shunsuke/ghalint/releases/tag/v0.2.10

**Comment by ponkio-o** [comment]
Thank you for fixing quickly!!!
